import java.util.Scanner;
import java.util.Random;

public class CasinoSeedDecoder {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        
        System.out.println("=== CASINO SEED DECODER ENGINE ===");
        System.out.println("Paste the first 15 space-separated numbers generated by standard Random:");
        System.out.print("Enter numbers: ");
        
        String inputLine = scanner.nextLine();
        String[] tokens = inputLine.trim().split("\\s+");
        
        if (tokens.length < 15) {
            System.out.println("Error: Please provide at least 15 numbers separated by spaces!");
            scanner.close();
            return;
        }

        int[] observedRolls = new int[15];
        for (int i = 0; i < 15; i++) {
            observedRolls[i] = Integer.parseInt(tokens[i]);
        }

        System.out.println("\nSearching 10,000,000 possible seeds for a match...");
        long foundSeed = -1;
        long startTime = System.currentTimeMillis();

        // EXPANDED BOUNDARY: Loops up to 10 Million instantly 
        for (long guessedSeed = 1; guessedSeed <= 10000000; guessedSeed++) {
            Random testPRNG = new Random(guessedSeed);
            boolean isMatch = true;

            for (int i = 0; i < 15; i++) {
                int testRoll = testPRNG.nextInt(6) + 1;
                if (testRoll != observedRolls[i]) {
                    isMatch = false;
                    break; // Optimization: Early exit if any number doesn't match
                }
            }

            if (isMatch) {
                foundSeed = guessedSeed;
                break; 
            }
        }

        long endTime = System.currentTimeMillis();

        if (foundSeed != -1) {
            System.out.println("\n🎉 SUCCESS! Server Seed Discovered: " + foundSeed);
            System.out.println("Time taken to crack: " + (endTime - startTime) + " ms");
            
            // Generate the 16th prediction
            Random predictorPRNG = new Random(foundSeed);
            for (int i = 0; i < 15; i++) {
                predictorPRNG.nextInt(6);
            }
            int predicted16thRoll = predictorPRNG.nextInt(6) + 1;
            
            System.out.println("================================================");
            System.out.println("🔮 PREDICTION: The 16th dice roll will be: " + predicted16thRoll);
            System.out.println("================================================");
            
        } else {
            System.out.println("\n❌ Seed not found in the tested search space.");
            System.out.println("If these came from SecureRandom, cracking is mathematically impossible!");
        }

        scanner.close();
    }
}
